# Content for the six AI service pages. Rendered by build-ai-services.py.
#
# Rules this copy follows (from the site's own history):
#  - Every proof point is something on /portfolio or a live page. No invented
#    statistics, client numbers or guarantees.
#  - LLMO is always "Large Language Model Optimization".
#  - Each page owns one search intent so it does not cannibalise an existing page:
#      /ai-consulting  -> "AI consulting services"   (/ai-consultant is the person)
#      /ai-advisory    -> "AI advisor" the human      (/ai-advisor is the voice bot)
#      /ai-seo         -> "AI SEO"                    (/llm-optimization is the deep LLMO page)

PAGES = []

# --------------------------------------------------------------- consulting
PAGES.append(dict(
slug="ai-consulting",
nav="AI Consulting",
title="AI Consulting Services | Strategy to Agents | Siamak Kalhor",
desc="AI consulting services for owners and executives: AI strategy, automation, agents, AI SEO and AI marketing, scoped to your numbers by a 40-year operator.",
og_kicker="AI CONSULTING SERVICES",
og_headline="AI consulting that starts|with your numbers.",
og_sub="Strategy · Automation · Agents · AI SEO · Marketing",
service_type="AI consulting",
eyebrow="AI Consulting Services",
h1='AI consulting that starts with your numbers, <span class="grad">not the newest tool.</span>',
sub="I help owners and leadership teams decide where artificial intelligence actually earns its keep, then build it: <strong>strategy, advisory, automation, AI agents, AI SEO and AI marketing.</strong> Forty years of market judgment, applied by someone who ships AI products of his own.",
glance=[("6","practice areas"),("8","AI products I've shipped"),("30 min","free strategy call"),("LA · Napa","and online worldwide")],
defn=dict(term="AI consulting",
  q="What is AI consulting?",
  a="AI consulting is outside expertise that helps a business decide where artificial intelligence will create measurable value, choose the right tools, implement them safely and train people to use them. Good AI consulting starts with the business problem (revenue, cost, speed or risk) and treats the technology as the last decision, not the first.",
  plain="Someone who has done this before tells you what's worth doing with AI, what isn't, and then helps you do it."),
why=dict(label="Why AI projects stall",h2='Most businesses don\'t have an AI problem. <span class="grad">They have a sequencing problem.</span>',
  lead="The tools are cheap and everywhere. What's scarce is knowing which problem to point them at, in which order, and who owns the result once the demo is over.",
  cards=[("◇","Tool-first buying","Subscriptions get bought before anyone has named the problem they're meant to solve. Six months later nobody can say what changed."),
         ("◎","Pilots that never graduate","A demo works in a meeting. Nobody owns turning it into something the team relies on, so it quietly dies."),
         ("⚡","Invisible to AI-led buyers","Customers ask ChatGPT, Gemini or Google's AI Overviews who to hire, and your business isn't in the answer."),
         ("◈","Teams left out of it","Staff either distrust the tools or use them quietly without guardrails. Both are risks you can't see.")]),
diagram=dict(type="hub",label="How the practice fits together",h2="Six practice areas, one constraint at a time",
  lead="Every engagement begins at the centre, with your numbers and your bottleneck, and reaches out only to the practice areas that move it.",
  center=("Your business","The one constraint that matters most right now"),
  nodes=[("AI Strategy","Where AI pays, ranked","#strategy"),("AI Advisory","A senior advisor on call","/ai-advisory"),("AI Automation","Hours reclaimed","/ai-automation"),
         ("AI Agents","Software that takes action","/ai-agents"),("AI SEO","Found in search and in answers","/ai-seo"),("AI Marketing","Volume without losing the brand","/ai-marketing")]),
help=dict(label="Practice areas",h2="What AI consulting with me covers",
  lead="Each area has its own page explaining the term in depth. Here is what each one produces. A deliverable can be checked; a capability can't.",
  cards=[("▦","AI Strategy & Roadmap","Finding where AI creates leverage in your business, and where it's a distraction.","A ranked list of AI opportunities with the value, cost, payback and risk of each, and a 90-day plan with named owners.",None),
         ("◇","AI Advisory","A senior, vendor-neutral advisor in your corner on a fixed cadence.","Vendor and proposal reviews, an AI use policy, leadership briefings and quarterly reviews.","/ai-advisory"),
         ("⟁","AI Automation","Taking the repetitive reading, sorting, typing and chasing out of your team's week.","Mapped and timed workflows, a measured pilot, then production automations with humans kept in the loop.","/ai-automation"),
         ("⬡","AI Agents","Custom agents that answer, book, follow up and update your systems.","An agent job description, a tested prototype, guardrails, human handoff and post-launch monitoring.","/ai-agents"),
         ("⚡","AI SEO","Ranking in Google and being cited by ChatGPT, Gemini, Perplexity and AI Overviews.","Technical fixes, entity and schema work, answer-first content and a monthly prompt-set measurement.","/ai-seo"),
         ("✦","AI Marketing","Marketing where AI handles the volume and your judgment keeps it true and on-brand.","A brand voice system, a content engine, AI-assisted paid media and reporting that starts with revenue.","/ai-marketing")]),
compare=dict(label="Choosing help",h2="Independent AI consultant, agency, vendor or do it yourself?",
  lead="Each is right for someone. Here is the honest comparison, including where I'm the wrong choice.",
  cols=["","Independent AI consultant","Agency","Software vendor","Do it yourself"],
  rows=[["Paid for","Judgment and outcomes","Hours of execution","Licences and seats","Your own time"],
        ["Recommends","Whatever fits, including nothing","What its team delivers","Its own product","What you've read"],
        ["Best when","You need the decision made right before spending","The plan is set and you need production capacity","You already know exactly which tool you need","The problem is small and the stakes are low"],
        ["Main risk","Senior time is limited, so scope must be focused","Retainers that outlive their usefulness","Lock-in to one way of working","Expensive mistakes made slowly"]]),
process=dict(label="How an engagement runs",h2="Diagnose, prove, then scale",
  steps=[("Diagnose","A free 30-minute call, then a baseline: your numbers, your workflows, the tools already in use, and how AI systems currently describe your business."),
         ("Prioritise","Every opportunity scored on value, effort, readiness and risk. Most businesses get a short list, and that's the point."),
         ("Pilot","One use case, a success metric agreed before work starts, and a timeline in weeks rather than quarters."),
         ("Implement","The production build: integrations, permissions, guardrails, documentation and training for the people who'll own it."),
         ("Measure & compound","A monthly review of what moved. When the first constraint is solved, we move to the next one.")]),
extra=dict(label="Engagement models",h2="Four ways to work together",lead="The same four models listed on the services page, so you can pick the one that matches the size of the problem.",
  items=[("The audit, once · $1,500","A fixed-scope diagnosis and plan. Many businesses should start here and stop here, executing the plan themselves."),
         ("Hourly consulting · $350–$450/hr","Second opinions, proposal reviews and decisions you want pressure-tested. No minimum commitment."),
         ("Monthly retainer","Continuous work across strategy, automation, content and AI visibility, with a defined deliverable list each month."),
         ("Fractional leadership","AI and marketing leadership rather than execution: owning the strategy, the budget and the vendors.")]),
fit=dict(good=["Owner-led or mid-size businesses with real revenue and a specific bottleneck","Legal, medical, dental, ecommerce, hospitality, contractors, textile and professional services","Leaders willing to change a process, not just add a tool","Teams that want to own the result after I leave"],
         bad=["“We need AI because our competitors have it”, with no problem named","Anyone wanting a guaranteed Google ranking or a guaranteed number of AI mentions","Requests for hundreds of AI-generated pages overnight","Projects where nobody internal will own the outcome"]),
proof=dict(label="Proof, not promises",h2="Advice from someone who builds",
  cards=[("SaaS","S.C.A.L.E.","My consulting method turned into software: it reads a website the way AI systems do, scores five dimensions and ranks what to fix.","https://scale.siamakconsulting.com/"),
         ("Legal AI","Your Legal Brain","My law-firm intake and operations platform, answering calls 24/7 in four languages and filing into Clio, Filevine or MyCase.","/ai-for-law-firms"),
         ("SaaS","Orchamind","The AI system that runs a contracting business: estimates, follow-ups, job costing and a voice assistant.","/portfolio"),
         ("8-year engagement","Blue Moon Fabrics","A single LA Fashion District store engineered into a national textile leader, the 100× build.","/bluemoon")]),
faq=[("How much does AI consulting cost?","Hourly consulting runs $350–$450 an hour with no minimum, which suits specific questions and second opinions. The AI Authority Audit is a fixed $1,500. Larger work is scoped at a fixed price after a diagnosis, and continuous work runs on a monthly retainer. The first 30-minute strategy call is free, and you can <a href=\"https://buy.stripe.com/cNi14o2yQaMUdbC3zX0kE03\">book and pay for a full hour</a> online. See <a href=\"/services\">services</a> for all four engagement models."),
     ("What's the difference between this page and your AI consultant page?","The <a href=\"/ai-consultant\">AI consultant</a> page is about me: who I am and how I think. This page is the service catalogue: what AI consulting covers, how an engagement runs and what you receive."),
     ("Do we need technical staff to work with an AI consultant?","No. Most of my clients are owner-led businesses without an IT department. I handle the technical side and hand over working systems with plain-English documentation and training."),
     ("Will AI replace my staff?","That's rarely the goal, and rarely the outcome. I design AI to remove the repetitive part of jobs (re-typing, sorting, chasing, first drafts) so people spend their time on judgment, relationships and the work customers actually pay for."),
     ("Which AI tools and models do you use?","I'm model-agnostic. I work with OpenAI, Anthropic's Claude, Google's Gemini and open-source models, and I prefer connecting to the software you already pay for over adding new subscriptions. The tool is chosen per job."),
     ("Do you work outside Los Angeles?","Yes. I'm based in Los Angeles with a presence in Napa Valley, and most engagements run online with clients across the United States and abroad.")],
cta=("Find the one AI move that matters most","Book a free 30-minute strategy call. You'll leave with a clear view of where AI pays in your business, even if you never hire me."),
))

# --------------------------------------------------------------- advisory
PAGES.append(dict(
slug="ai-advisory",
nav="AI Advisory",
title="AI Advisor for Business Owners | Fractional AI Advisory",
desc="A senior AI advisor on your side: vendor vetting, an AI roadmap, policy and team adoption, with no software to sell. Fractional AI advisory by Siamak Kalhor.",
og_kicker="FRACTIONAL AI ADVISORY",
og_headline="An AI advisor with nothing|to sell you but judgment.",
og_sub="Roadmap · Vendor vetting · Policy · Board briefings",
service_type="AI advisory",
eyebrow="AI Advisor · Fractional AI Advisory",
h1='An AI advisor with <span class="grad">nothing to sell you</span> but judgment.',
sub="Every vendor now has an AI pitch. I sit on your side of the table: <strong>vetting tools, setting the roadmap, writing the rules your team works by and briefing leadership</strong>, on a fixed cadence and without a full-time salary.",
glance=[("Fractional","weekly or fortnightly"),("Neutral","no product to push"),("Board-ready","leadership briefings"),("30 min","free first call")],
defn=dict(term="AI advisor",
  q="What is an AI advisor?",
  a="An AI advisor is a senior, independent expert who guides a business owner or leadership team through artificial-intelligence decisions: which opportunities to pursue, which vendors to trust, what policies to set and how to measure results. Unlike a vendor or an agency, an AI advisor is paid for judgment, not for selling software or hours of execution.",
  plain="The experienced person you call before you sign the AI contract, and again when you want to know whether it's working."),
note='<b>Looking for the AI Advisor you can talk to?</b> My free 24/7 <a href="/ai-advisor">AI Advisor</a> is a voice and video assistant trained on my work, available in 20 languages. This page is about working with me directly as your human advisor.',
why=dict(label="The decisions",h2='Four decisions an AI advisor <span class="grad">helps you get right</span>',
  lead="Most of the value of an advisor is in the expensive mistakes you don't make, which is why the work is organised around decisions rather than tasks.",
  cards=[("▦","Buy, build or wait?","Some AI is ready for your business today, some is a year from useful, and some will never pay. Knowing which is which is the first decision."),
         ("◇","Which vendor?","Proposals look alike and pricing hides in usage fees. I read them like a buyer, not a seller."),
         ("◈","What's allowed?","Which tools staff may use, what data never goes into them and what you disclose to customers, written down before something goes wrong."),
         ("◎","Is it working?","A metric agreed before money is spent, and someone independent checking it afterwards.")]),
diagram=dict(type="filter",label="How I filter AI decisions",h2="Everything passes through four gates",
  lead="Pitches, staff ideas, competitor moves and headlines all go through the same filter, and come out with one of four verdicts.",
  inputs=["Vendor pitches","Staff ideas","Competitor moves","Headlines & hype"],
  gates=[("Business value","Does it move revenue, cost, speed or risk?"),("Readiness","Are the data, process and people ready?"),("Risk & compliance","What could go wrong, and who is exposed?"),("Payback","When does it pay for itself, all-in?")],
  outputs=[("Do now","good"),("Pilot first","mid"),("Park","low"),("Never","no")]),
help=dict(label="What I do as your advisor",h2="Fractional AI advisory, deliverable by deliverable",
  lead="An advisory relationship should leave a paper trail you can hold me to. These are the artifacts it produces.",
  cards=[("▦","AI Roadmap","Where AI fits in your business over the next twelve months, in order.","A roadmap ranked by value and readiness, revisited every quarter as the tools and your business change.",None),
         ("◇","Vendor & Proposal Review","A buyer's read of any AI proposal, contract or demo before you commit.","A written review: what it really does, the all-in cost including usage fees, red flags and the questions to ask.",None),
         ("◈","AI Use Policy","Clear rules for how your team uses AI with customer and company data.","A plain-English policy covering approved tools, data that never goes in, approval paths and disclosure, ready for your counsel to review.",None),
         ("◎","Leadership & Board Briefings","What changed in AI this quarter that matters to your business, and what didn't.","A short quarterly briefing and a standing agenda item, so leadership decides from facts rather than headlines.",None),
         ("⟁","Team Adoption","Getting people fluent and confident, with guardrails that protect the brand.","Role-based training and office hours, built around your own work rather than generic examples.","/llmo-training"),
         ("⬡","Vendor & Agency Oversight","Holding the people you already pay to measurable outcomes.","A monthly scorecard for each AI vendor and agency against the metric they committed to.",None)]),
compare=dict(label="Similar roles",h2="AI advisor, AI consultant, fractional CTO or vendor?",
  lead="These titles get used interchangeably. They're different jobs, and the right one depends on what you need.",
  cols=["","AI advisor","AI consultant","Fractional CTO","AI vendor"],
  rows=[["Focus","Decisions and direction","Defined projects and builds","Your technology stack and engineers","Its own product"],
        ["Cadence","Ongoing, a few hours a month","Project-based","Ongoing, part-time","Sales cycle, then support"],
        ["Best when","Leadership needs a trusted second opinion on every AI move","You know the problem and need it solved","You have a software team to lead","You've already chosen the solution"],
        ["Paid for","Judgment","Delivery","Technical leadership","Licences"]]),
process=dict(label="How advisory works",h2="From first call to standing cadence",
  steps=[("Intake call","A free 30 minutes to understand the business, the pressure you're under and the AI decisions on the table."),
         ("30-day baseline","An inventory of the AI already in use (including the tools staff adopted on their own), spend, data flows and the opportunities worth examining."),
         ("Roadmap","The ranked roadmap and the first policy draft, agreed with leadership."),
         ("Standing cadence","A weekly or fortnightly slot plus access between sessions for the decisions that can't wait."),
         ("Quarterly review","A written review of what worked, what to stop and what's next, measured against the metrics we set.")]),
fit=dict(good=["Owners and executives facing AI decisions without an in-house expert","Firms receiving AI pitches from vendors and agencies they can't evaluate","Regulated or confidential work (legal, medical, financial) that needs a policy first","Boards that want a clear, independent read on AI risk and opportunity"],
         bad=["Teams that only need hands-on build capacity; see <a href=\"/ai-agents\">AI agents</a> or <a href=\"/ai-automation\">automation</a>","Anyone wanting an advisor to sign off on a decision already made","Organisations looking for a full-time employee","Requests for legal advice; I work alongside your counsel, not instead of them"]),
proof=dict(label="Why my advice is grounded",h2="I advise on what I've built",
  cards=[("8 products","AI-native products shipped","S.C.A.L.E., Orchamind, AisleBird, ResBizAI, Textile Wizard and more, designed, coded and launched end to end.","/portfolio"),
         ("Legal AI","Your Legal Brain","Built for confidential, regulated work: 24/7 intake under attorney supervision, designed around compliance from day one.","/ai-for-law-firms"),
         ("Voice AI","The AI Advisor","My own voice and video advisor in 20 languages: proof that I know what these systems can and can't do in front of real customers.","/ai-advisor"),
         ("40 years","Marketing leadership","Four decades of fractional CMO and growth work, which is where the judgment about vendors, budgets and people comes from.","/about-us")]),
faq=[("What does a fractional AI advisor do?","A fractional AI advisor gives you senior AI judgment for a few hours a month instead of a full-time hire: setting the AI roadmap, reviewing vendor proposals, writing your AI use policy, briefing leadership and checking whether the AI you've bought is paying off."),
     ("How is this different from your AI Advisor voice assistant?","The <a href=\"/ai-advisor\">AI Advisor</a> is a free AI you can talk to at any hour about growth and AI visibility. This page is about engaging me personally, as a human advisor, for decisions specific to your business."),
     ("How much of my time does it take?","Typically one standing session a week or fortnight, plus short questions in between. The baseline month asks a little more, mostly for access to people and numbers."),
     ("Can you advise our board or partners?","Yes. Quarterly briefings for boards, partners and leadership teams are a standard part of the engagement, written so non-technical directors can make decisions from them."),
     ("Is your AI use policy legal advice?","No. It's an operational policy written in plain English. For regulated businesses I recommend having your counsel review it, and I'm happy to work alongside them."),
     ("Do you recommend your own products?","Only when they're genuinely the best fit, and I'll say so plainly when they are. Most of the time the right answer is a tool you already own, a mainstream product or doing nothing yet.")],
cta=("Get a second opinion before the next AI decision","Start with a free 30-minute call. Bring the proposal, the pitch or the question that's been sitting on your desk."),
))

# --------------------------------------------------------------- automation
PAGES.append(dict(
slug="ai-automation",
nav="AI Automation",
title="AI Automation Consulting | Automate Intake & Operations",
desc="AI automation consulting that finds the hours worth reclaiming (lead response, intake, documents, reporting) and builds it with humans in the loop.",
og_kicker="AI AUTOMATION CONSULTING",
og_headline="Automate the work nobody|should do by hand.",
og_sub="Intake · Documents · Follow-up · Reporting",
service_type="AI automation consulting",
eyebrow="AI Automation Consulting",
h1='Automate the work <span class="grad">nobody should be doing by hand.</span>',
sub="Lead replies at 11pm. Re-typing PDFs into spreadsheets. Chasing the same five follow-ups every week. I find the hours worth reclaiming, <strong>build the automation, and keep a human wherever judgment matters.</strong>",
glance=[("Human","in the loop by design"),("Your tools","not a new platform"),("Pilot","first, then scale"),("Hours","the unit we measure")],
defn=dict(term="AI automation",
  q="What is AI automation?",
  a="AI automation uses artificial intelligence to complete steps in a business process that used to need a person to read, decide or write, such as sorting incoming email, extracting data from documents, drafting replies or qualifying leads. Traditional automation follows fixed rules. AI automation can handle messy, unstructured inputs and make judgment calls within limits you set.",
  plain="Software that can read, decide and draft, so your people only touch the parts that need a person."),
why=dict(label="Rules vs. AI",h2='Why AI automation <span class="grad">reaches work rules never could</span>',
  lead="Classic automation broke the moment an email was worded differently or a PDF arrived in a new layout. Language models change that, which is why the list of automatable work just got much longer.",
  cards=[("◇","Rule-based automation","“If the form says X, do Y.” Fast and reliable, but brittle: it fails on anything it wasn't told to expect."),
         ("⚡","AI automation","Reads the email, understands the request, extracts what matters and drafts the next step, even when every input looks different."),
         ("◈","The combination","The best systems use rules where things are predictable and AI only where judgment is needed. That's cheaper, faster and easier to audit."),
         ("◎","The human checkpoint","When the AI isn't confident, or the stakes are high, the task routes to a person with everything already prepared.")]),
diagram=dict(type="flow",label="Anatomy of an automation",h2="What a well-built AI automation actually does",
  lead="Six stages, with a person placed exactly where the stakes call for one.",
  nodes=[("Trigger","A form, email, call, file or schedule"),("AI reads","Classifies the request and extracts the data"),("AI drafts","Writes the reply, record or summary"),("Human check","Only when confidence is low or stakes are high"),("Action","Updates your CRM, calendar or books"),("Log","Every step recorded and measured")],
  highlight=3),
help=dict(label="Where automation pays first",h2="The workflows I automate most",
  lead="Ranked roughly by how fast they pay back for the businesses I work with.",
  cards=[("⚡","Speed-to-lead & intake","Every inquiry answered in seconds, qualified and booked, including nights and weekends.","Instant replies, qualifying questions, calendar booking and a clean record in your CRM.",None),
         ("▦","Document processing","Invoices, purchase orders, intake forms and packing lists read and entered without re-typing.","Structured data pulled from PDFs and email into your accounting or operations system, with exceptions flagged.",None),
         ("⟁","Follow-up & nurture","The follow-ups that fall through the cracks, sent on time and in your voice.","Sequences triggered by what the customer did, with drafts you approve for anything sensitive.",None),
         ("◎","Scheduling & dispatch","Appointments, crews and reminders coordinated without the phone tag.","Booking, rescheduling, reminders and no-show follow-up connected to your calendar.",None),
         ("✦","Reporting","The weekly numbers assembled for you, with a plain-English summary of what changed.","Automated dashboards and a written weekly brief: what's up, what's down, what needs a decision.",None),
         ("◈","Internal knowledge assistant","Staff questions answered from your own procedures, price lists and policies.","An assistant grounded in your documents that cites its source and says when it doesn't know.",None)]),
compare=dict(label="Measure before you build",h2="How I decide what to automate",
  lead="Every candidate workflow gets the same scoring, so the first automation is the one with the clearest payback.",
  cols=["Factor","What I measure","Why it matters"],
  rows=[["Volume","How often the task happens each week","Frequent tasks pay back fastest"],
        ["Time","Minutes of human effort each time","Volume × time = hours reclaimed"],
        ["Error cost","What a mistake costs in money or trust","High-cost errors need a human checkpoint"],
        ["Input mess","How varied the inputs are","Messy inputs need AI; tidy inputs only need rules"],
        ["Speed value","Whether a faster response wins business","Lead response is usually worth the most"]]),
process=dict(label="How I build it",h2="Map, score, pilot, harden, hand over",
  steps=[("Map the process","I watch the work being done and time it. The real process is rarely the one in the manual."),
         ("Score the candidates","Volume, time, error cost and input mess, so we start where the payback is clearest."),
         ("Pilot one workflow","A single automation with a success metric agreed up front: hours saved, response time or error rate."),
         ("Harden it","Guardrails, fallbacks, permissions and logging, so it keeps working when inputs get strange."),
         ("Train & hand over","Documentation, a named internal owner and a monthly check that it's still paying off.")]),
extra=dict(label="Restraint",h2="What I won't automate",lead="Knowing where to stop is part of the job.",
  items=[("Final professional judgment","Legal, medical and financial decisions stay with a qualified person. AI prepares; people decide."),
         ("A broken process","Automating a bad process just makes the mess faster. We fix the process first."),
         ("The relationships clients pay for","If your best customers value talking to you, automation should give you more time for them, not replace you."),
         ("Anything you couldn't explain to a customer","If you'd be uncomfortable describing how a decision was made, it shouldn't be automated.")]),
fit=dict(good=["Teams losing hours to re-typing, sorting, chasing and copy-paste","Businesses whose leads wait hours, or overnight, for a reply","Offices drowning in PDFs, forms and email attachments","Owners who want measurable time back, not a technology project"],
         bad=["Processes nobody can describe yet; we map them first","Expectations of zero human involvement in high-stakes work","Teams unwilling to change how a task is done","Automation for its own sake, with no hours or revenue at stake"]),
proof=dict(label="Automations I've shipped",h2="Built into my own products",
  cards=[("ERP","Textile Wizard","AI reads PDF purchase orders, and packing lists become invoices with no re-typing, for fabric distributors.","/textile-wizard"),
         ("SaaS","Orchamind","AI writes estimates and follow-ups and flags jobs going over budget for contracting businesses.","/portfolio"),
         ("Legal AI","Your Legal Brain","Intake calls answered, qualified and drafted straight into Clio, Filevine or MyCase.","/ai-for-law-firms"),
         ("SaaS","ResBizAI","Restaurant scheduling, inventory and daily P&L, run by voice.","/portfolio")]),
faq=[("What can AI automation do for a small business?","The biggest wins are usually lead response (answering and qualifying inquiries instantly), document processing (reading invoices, orders and forms into your systems), follow-ups, scheduling and weekly reporting. Together they often hand back many hours a week."),
     ("How do you keep AI automation from making mistakes?","By design: AI handles only the steps that need judgment, rules handle the rest, low-confidence cases route to a person, and every action is logged. We also test on your real historical examples before anything goes live."),
     ("Will it work with the software we already use?","Usually, yes. I prefer connecting to the tools you already pay for (email, calendar, CRM, accounting, practice-management systems) through standard automation platforms or custom code, rather than moving you to something new."),
     ("Is our data used to train AI models?","I set automations up on business-grade API access, where the major AI providers' terms state your data isn't used to train their models by default. I also review each vendor's data terms with you before anything sensitive flows through."),
     ("How long does an automation pilot take?","Pilots are scoped in weeks, not quarters, and the success metric is agreed before work begins. If the pilot doesn't hit it, you know quickly and cheaply."),
     ("What does AI automation cost?","It depends on the number of workflows and integrations. After the mapping stage you get a fixed-price build estimate plus the expected monthly running cost (software and AI usage), so you can compare it with the hours saved.")],
cta=("Find the hours hiding in your week","Book a free 30-minute call. Bring the task your team complains about most; that's usually the right first automation."),
))

# --------------------------------------------------------------- agents
PAGES.append(dict(
slug="ai-agents",
nav="AI Agents",
title="AI Agents for Business | Custom AI Agent Development",
desc="What AI agents are, what they can safely do, and how I design, build and monitor custom agents for voice intake, sales follow-up and operations.",
og_kicker="CUSTOM AI AGENTS",
og_headline="AI agents that do the work|and know when to hand it back.",
og_sub="Voice intake · Follow-up · Support · Operations",
service_type="AI agent development",
eyebrow="AI Agents for Business",
h1='AI agents that <span class="grad">do the work</span> and know when to hand it back.',
sub="An AI agent doesn't just answer questions; it takes steps. It answers the call, checks the calendar, books the appointment and updates the CRM. I <strong>design, build and monitor custom AI agents</strong> for owner-led and mid-size businesses, the same way I built my own.",
glance=[("Voice","chat & back-office agents"),("Built","not just advised on"),("Guardrails","and human handoff"),("Monitored","after launch")],
defn=dict(term="AI agent",
  q="What is an AI agent?",
  a="An AI agent is software powered by a large language model that pursues a goal by planning steps, using tools (a calendar, CRM, database or phone line) and acting on the results, rather than only replying to a message. A well-built business agent works within clear permissions, keeps a record of what it did, and hands off to a person when a situation is uncertain or high-stakes.",
  plain="A digital team member that can take actions, not just chat, and knows when to call you."),
why=dict(label="Chatbot vs. agent",h2='Why agents are different from <span class="grad">the chatbots you\'ve already tried</span>',
  lead="Most businesses have met a website chatbot that could only repeat the FAQ. Agents are a different category of software, and the difference is action.",
  cards=[("◇","Chatbots answer","They match a question to a scripted reply. Useful for hours and directions; useless the moment the conversation goes off-script."),
         ("⟁","Automations execute","They run a fixed sequence reliably, but can't handle anything they weren't built to expect."),
         ("⬡","Agents decide and act","They understand the request, choose which tool to use, take the step and check the result, inside limits you set."),
         ("◈","Good agents escalate","The mark of a well-built agent is knowing what it shouldn't handle, and passing that to a person cleanly.")]),
diagram=dict(type="anatomy",label="Anatomy of a business agent",h2="Six parts every agent I build has",
  lead="The model is only the middle. What makes an agent safe and useful is everything around it.",
  core=("Reasoning loop","Plan → act → check the result → repeat until the goal is met or it's time to hand off"),
  left=[("Goal & instructions","The agent's job description: what it's for and how it should behave"),("Tools","Calendar, CRM, phone, email, database, the actions it's allowed to take"),("Knowledge","Your FAQs, policies, price lists and history, cited when used")],
  right=[("Guardrails","Permissions, spending and promise limits, and topics it must refuse"),("Human handoff","Clear rules for when a person takes over, with full context passed along"),("Logs & evaluation","Every conversation and action recorded, reviewed and scored")]),
help=dict(label="Agents I build",h2="The AI agents businesses ask me for most",
  lead="Each starts from a real workflow in your business, not from a template.",
  cards=[("☎","Voice receptionist & intake","Answers every call 24/7, qualifies the caller, books the appointment and routes the urgent ones.","A phone or web voice agent with your scripts, your calendar and a clean record of every call.","/ai-for-law-firms"),
         ("⟁","Sales follow-up agent","Follows up every lead on time, answers questions and moves serious buyers to a meeting.","Personalised follow-up across email or text, with handoff to a salesperson when intent is high.",None),
         ("◎","Customer support agent","Resolves the common questions from your own knowledge base and escalates the rest.","An agent grounded in your documents that cites sources and hands complex cases to staff.",None),
         ("▦","Operations agent","Estimates, scheduling, job costing and status updates, the back-office work that never ends.","An agent connected to your operational data that drafts, flags and updates for your team to approve.",None),
         ("✦","Research & analysis agent","Gathers data from many sources and turns it into a decision-ready report.","Repeatable research reports in minutes, with sources listed so every claim can be checked.",None),
         ("◇","Expert advisor agent","Your expertise, available around the clock to prospects and clients.","An agent trained on your methods, voice and FAQs, with clear limits on what it may advise.","/ai-advisor")]),
compare=dict(label="Know what you're buying",h2="Chatbot, automation or AI agent?",
  lead="Choosing the simplest tool that does the job is cheaper and safer. Sometimes that isn't an agent.",
  cols=["","Chatbot","Automation","AI agent"],
  rows=[["How it works","Scripted replies to expected questions","A fixed sequence of steps","Plans and chooses steps toward a goal"],
        ["Handles the unexpected","No","No","Yes, within its guardrails"],
        ["Takes actions","Rarely","Yes, the same ones every time","Yes, chosen to fit the situation"],
        ["Best for","Hours, directions, simple FAQs","Predictable, repetitive tasks","Conversations and multi-step work that varies"],
        ["Needs","Little upkeep","Occasional maintenance","Testing, monitoring and review"]]),
process=dict(label="How I build agents",h2="Hire it like a person, test it like software",
  steps=[("Write the job description","Tasks, tools, limits and escalation rules, written the way you'd brief a new hire."),
         ("Prototype on real examples","Your actual calls, emails and questions, not invented demos."),
         ("Evaluate before launch","A test set of real and edge-case conversations, scored for accuracy and tone until it passes."),
         ("Launch with guardrails","Limited scope first, human review on sensitive actions and full logging from day one."),
         ("Monitor & improve","Weekly review of transcripts and failure cases, with the agent's instructions tightened as we learn.")]),
extra=dict(label="Responsible by design",h2="What my agents never do",lead="These limits are built in, not bolted on.",
  items=[("Make promises outside your policy","Discounts, refunds, timelines and guarantees stay inside limits you define."),
         ("Give professional advice","Legal, medical and financial questions are captured and routed to a qualified person."),
         ("Reach beyond their job","Each agent sees only the data and tools its role requires."),
         ("Hide that they're AI","I recommend clear disclosure, and California law requires it in certain sales and election contexts.")]),
fit=dict(good=["High call or message volume, especially after hours","Repetitive conversations that still need some judgment","Businesses serving customers in more than one language","Teams that will review the agent's work during its first weeks"],
         bad=["A single simple FAQ; a chatbot or a better web page may be enough","Fully autonomous agents making high-stakes decisions","Projects with no one to review transcripts after launch","Use cases that depend on the agent pretending to be human"]),
proof=dict(label="Agents in production",h2="Agents I built and run myself",
  cards=[("Voice + video","The AI Advisor","My own advisor agent, trained on 40 years of work, talking with visitors in 20 languages by voice or video avatar.","/ai-advisor"),
         ("Legal intake","Your Legal Brain","Answers law-firm calls 24/7 in English, Spanish, Farsi and Armenian, qualifies the matter and files the intake.","/ai-for-law-firms"),
         ("Research","K2 Parcel Finder","Turns any California address into an investor-grade land feasibility report in under two minutes.","/portfolio"),
         ("Consumer AI","Napa Wino","An AI sommelier that plans a tasting day across 50+ wineries from a plain-English description.","/portfolio")]),
faq=[("What's the difference between an AI agent and a chatbot?","A chatbot replies with scripted answers. An AI agent understands the request, decides what to do, uses tools such as your calendar or CRM to do it, and checks the result. It can complete a task, like booking an appointment, rather than just talking about it."),
     ("Are AI agents safe to use with customers?","They can be, when they're built with narrow permissions, clear limits on what they may promise, human handoff rules, full logging and testing on real conversations before launch. Those safeguards are part of every agent I build."),
     ("What can an AI agent connect to?","Most business systems with an API or integration: phone lines, email, calendars, CRMs, help desks, databases, practice-management systems such as Clio, Filevine and MyCase, and your own documents."),
     ("How much does it cost to build an AI agent?","It depends on the number of tools it connects to and how much testing the use case needs. After discovery you get a fixed build price plus an estimate of monthly running costs (AI model usage, telephony and hosting), so the all-in number is clear before you commit."),
     ("Will customers know they're talking to AI?","I recommend telling them, and in some situations it's required. California's bot-disclosure law, for example, covers bots used on large online platforms to sell goods or services or to influence a vote, and similar rules are spreading. Clear disclosure also builds trust; customers mostly care that they get a fast, correct answer."),
     ("How long does it take to build an AI agent?","A focused first agent typically moves from job description to supervised launch in weeks. The timeline depends mostly on integrations and on how much real conversation data is available for testing.")],
cta=("Put an agent on the work that never stops","Book a free 30-minute call. We'll identify the one conversation or task where an agent would pay back fastest."),
))

# --------------------------------------------------------------- ai seo
PAGES.append(dict(
slug="ai-seo",
nav="AI SEO",
title="AI SEO | Rank in Google, Get Cited by ChatGPT & AI Overviews",
desc="AI SEO explained: its two meanings, what changed with AI Overviews and answer engines, and the work that gets your business ranked in Google and cited by AI.",
og_kicker="AI SEO",
og_headline="Rank in Google|and get named by AI.",
og_sub="AI Overviews · ChatGPT · Gemini · Perplexity",
service_type="AI SEO",
eyebrow="AI SEO",
h1='AI SEO: rank in Google <span class="grad">and get named by AI.</span>',
sub="Buyers now get answers before they get links, from Google's AI Overviews, ChatGPT, Gemini, Claude and Perplexity. <strong>AI SEO is the work that keeps you in both places:</strong> the results page and the answer.",
glance=[("2","surfaces: results & answers"),("3","layers: technical, entity, content"),("Real","prompts, re-measured"),("Zero","ranking guarantees")],
defn=dict(term="AI SEO",
  q="What is AI SEO?",
  a="AI SEO is search engine optimization for an era when AI systems answer the query. The term has two meanings: using AI tools to do SEO work faster, and optimizing a website so that AI-powered search (Google AI Overviews, ChatGPT search, Gemini and Perplexity) can find, trust and cite it. The second meaning matters more, because it decides whether your business appears in the answer at all.",
  plain="Making sure that when someone asks a search engine or an AI about what you do, your business is part of the answer."),
why=dict(label="Two meanings",h2='“AI SEO” means two things. <span class="grad">Only one is an advantage.</span>',
  lead="When an agency says it does AI SEO, ask which one it means. Both are useful; only one is hard to copy.",
  cards=[("◇","Meaning 1: AI for SEO","Using AI to research keywords, cluster topics, draft outlines and run audits. Faster, but everyone has the same tools, so it's quickly becoming table stakes."),
         ("⚡","Meaning 2: SEO for AI","Making your business something AI systems can find, verify and quote. That's where visibility is won or lost now, and it compounds."),
         ("◈","The shared foundation","Both rest on the same base: a crawlable site, a clear identity, structured data and facts that other sources confirm."),
         ("◎","Why it's urgent","When the answer appears above the links, being ranked fourth may mean never being seen. Being cited in the answer is the new first position.")]),
diagram=dict(type="lanes",label="How the two systems decide",h2="Classic search and AI answers, side by side",
  lead="Two pipelines, one foundation. AI SEO works on both lanes and on the ground they share.",
  lanes=[("Classic search",["Crawl","Index","Rank","Click"]),("AI answers",["Retrieve","Ground","Synthesize","Cite"])],
  base=["Crawlable site","Clear entity","Structured data","Quotable facts","Third-party corroboration"]),
help=dict(label="The work",h2="What AI SEO with me includes",
  lead="Three layers, in the order that moves fastest: technical first, then identity, then content and authority.",
  cards=[("▦","Technical foundation","Making sure search engines and AI crawlers can actually reach and read you.","Crawlability and rendering fixes, speed, a deliberate robots.txt policy for AI crawlers, and clean sitemaps.",None),
         ("◈","Entity & structured data","Teaching machines exactly who you are, what you do and where.","Organization, Person, Service and FAQ schema, consistent name/address/phone and linked profiles across the web.",None),
         ("⚡","Answer-first content","Pages that state the facts a model can quote, not just keywords.","A question-led content plan, direct definitions, comparison tables and FAQs, drafted with AI and edited by a person.",None),
         ("⬡","Off-site corroboration","AI trusts what other sources confirm about you.","Directory, review and profile cleanup, plus earned mentions on the sources AI systems draw from.",None),
         ("◇","AI-readable declarations","Telling AI systems directly what's true about your business.","An llms.txt file and a facts page written for machines, kept consistent with everything else.","/llm-info"),
         ("◎","Measurement","Proving what moved, in Google and in AI answers.","A fixed prompt set re-run monthly across major AI assistants, alongside Search Console data.",None)]),
compare=dict(label="What changes",h2="Classic SEO vs. AI SEO",
  lead="Most of classic SEO still matters. What changes is the goal, the unit and how success is measured.",
  cols=["","Classic SEO","AI SEO"],
  rows=[["Goal","Rank a page in the results","Be cited or named in the answer"],
        ["Unit of work","Keywords","Questions and entities"],
        ["Key signals","Relevance and links","Clarity, consistency across sources, corroboration"],
        ["Content style","Comprehensive pages","Direct answers and facts a model can quote"],
        ["Measured by","Rankings and clicks","Mention and citation rate across a prompt set, plus clicks"]]),
process=dict(label="How it runs",h2="Baseline, fix, clarify, publish, corroborate",
  steps=[("Baseline","Search Console data plus a prompt set run across ChatGPT, Gemini, Perplexity, Claude and Google's AI Overviews: who gets named today, and who doesn't."),
         ("Fix blockers","Crawl, rendering and indexing problems first. They're fast, cheap and nothing else works until they're gone."),
         ("Clarify the entity","Schema, consistent business facts and linked profiles, so every source describes you the same way."),
         ("Publish answers","Content built from the questions buyers actually ask, written to be quotable."),
         ("Corroborate & re-measure","External mentions and reviews, then the same prompt set re-run, so progress is measured rather than claimed.")]),
fit=dict(good=["Businesses whose buyers research before they call","Firms already ranking in Google but missing from AI answers","Brands with inconsistent listings, profiles or descriptions","Teams that want measurement, not activity reports"],
         bad=["Anyone wanting guaranteed rankings or guaranteed AI mentions","Requests to mass-produce AI pages for keywords","Businesses unwilling to fix inaccurate listings and profiles","Expectations of results within days; authority takes months"]),
proof=dict(label="Go deeper",h2="Related tools and explainers",
  cards=[("Free scan","S.C.A.L.E.","Score your site the way AI systems read it, across five dimensions, with a ranked fix list.","https://scale.siamakconsulting.com/"),
         ("Deep dive","Large Language Model Optimization","The full LLMO discipline: getting cited by ChatGPT, Gemini and Claude.","/llm-optimization"),
         ("Explainer","SEO vs. LLMO","Where classic SEO and Large Language Model Optimization overlap, and where they split.","/seo-vs-llmo"),
         ("Explainer","AI visibility","Why a competitor gets named and you don't, and how that's measured.","/ai-visibility")]),
faq=[("Is AI SEO the same as LLMO, GEO or AEO?","They overlap heavily. Large Language Model Optimization (LLMO), Generative Engine Optimization (GEO) and Answer Engine Optimization (AEO) all describe the “SEO for AI” half of AI SEO. AI SEO is the broader label that also includes classic Google SEO. See <a href=\"/seo-vs-llmo\">SEO vs. LLMO</a> for the full comparison."),
     ("Does traditional SEO still matter?","Yes. AI search features retrieve from web indexes, so pages that can't be crawled, indexed and trusted rarely get cited. AI SEO builds on classic SEO; it doesn't replace it."),
     ("Can you guarantee ChatGPT or Google will recommend my business?","No, and you should be wary of anyone who does. No one controls these systems. What I can do is remove what's blocking you, make your business unambiguous and well-corroborated, and measure the change honestly."),
     ("Should I block AI crawlers?","It depends on which ones. Crawlers that power AI search (OpenAI's OAI-SearchBot, for example) are how your pages get cited in answers. Crawlers used for model training, such as GPTBot, are a separate choice. Blocking everything can remove you from AI answers entirely."),
     ("How do you measure AI SEO results?","Two ways: Search Console for classic search, and a fixed set of real buyer questions run monthly across the major AI assistants, tracking whether and how your business is named."),
     ("How long does AI SEO take?","Technical fixes can show up within weeks of being recrawled. Entity clarity and external corroboration take months, because they depend on other sources and on systems updating. Plan in quarters, measure monthly.")],
cta=("See how AI search sees your business today","Run a free S.C.A.L.E. scan, or book a 30-minute call and we'll look at your Search Console and AI answers together."),
))

# --------------------------------------------------------------- ai marketing
PAGES.append(dict(
slug="ai-marketing",
nav="AI Marketing",
title="AI Marketing Consulting | Strategy for the Generative AI Era",
desc="AI marketing consulting from a 40-year marketer: where AI sharpens research, content and paid media, where it erodes your brand, and the fix.",
og_kicker="AI MARKETING CONSULTING",
og_headline="AI marketing that sharpens|your brand.",
og_sub="Strategy · Voice · Content · Paid media · Measurement",
service_type="AI marketing consulting",
eyebrow="AI Marketing Consulting",
h1='AI marketing that <span class="grad">sharpens your brand</span> instead of flattening it.',
sub="AI can research, draft, target and report faster than any team. Used without a strategy, it makes you sound like everyone else using the same tools. <strong>I build the marketing system where AI does the volume and your judgment decides what's true, on-brand and worth saying.</strong>",
glance=[("40 yrs","in marketing"),("Strategy","before tools"),("Your voice","protected"),("Revenue","not reach")],
defn=dict(term="AI marketing",
  q="What is AI marketing?",
  a="AI marketing is the use of artificial intelligence across the marketing function (research, segmentation, content creation, advertising, personalization and measurement) to make decisions faster and execute at a scale a small team couldn't reach alone. It also means marketing to buyers whose research now runs through AI assistants, which changes how brands get discovered and chosen.",
  plain="Using AI to do better marketing, and doing marketing that still works when your customers ask an AI first."),
why=dict(label="The trade-off",h2='Where AI makes marketing better, and <span class="grad">where it quietly makes it worse</span>',
  lead="The same tool that writes a month of posts in an afternoon can also erase everything that made your brand recognisable. The difference is the system around it.",
  cards=[("⚡","Where AI helps","Research, first drafts, variations for testing, audience analysis, ad iteration and reporting: speed and volume a small team never had."),
         ("◈","Where AI hurts","Sameness. When everyone prompts the same tools, the output converges. Generic content is invisible to people and to AI systems alike."),
         ("◇","Where it's risky","Confident errors: invented facts, claims you can't support and messages that drift off-brand without anyone noticing."),
         ("◎","What fixes it","Positioning first, a written voice system, human editing on everything public and measurement tied to revenue.")]),
diagram=dict(type="loop",label="The operating model",h2="The AI marketing loop: AI does, you decide",
  lead="Five stages, run every month. At each one, AI handles the volume and a person makes the call.",
  nodes=[("Research","AI does: scans markets, reviews, competitors and AI answers","You decide: which insight matters"),
         ("Position","AI does: tests angles and messages","You decide: what you stand for"),
         ("Create","AI does: drafts and variations","You decide: what's true and on-brand"),
         ("Distribute","AI does: targeting, bidding and scheduling","You decide: budget and channels"),
         ("Measure","AI does: assembles data and spots patterns","You decide: what to stop and scale")]),
help=dict(label="How I help",h2="AI marketing consulting, deliverable by deliverable",
  lead="Strategy first, then the system, then the execution, with every artifact something you keep.",
  cards=[("▦","AI Marketing Strategy & Audit","Where AI belongs in your marketing, and what to stop doing.","A written audit of your channels, spend and content, plus a plan ranked by revenue impact.",None),
         ("◇","Brand Voice System","Making AI output sound like you, every time, from anyone on the team.","A voice guide, approved examples and a prompt library tuned to your brand and offers.",None),
         ("⚡","Content Engine","Content that answers real buyer questions and is quotable by AI.","A question-led content plan, AI-assisted drafts, human edits, schema and short-form video scripts.","/ai-seo"),
         ("◈","AI-Assisted Paid Media","Google and Meta campaigns run against cost per customer, not clicks.","Account structure, conversion tracking tied to revenue and AI-generated creative variations tested methodically.",None),
         ("⟁","Lead Response & Nurture","Making sure the leads marketing creates actually get answered.","Instant response, follow-up sequences and tracking from first inquiry to closed customer.","/ai-automation"),
         ("◎","Measurement That Means Something","Reporting that starts with inquiries and revenue.","A monthly dashboard and written review: what produced customers, what to cut and what to scale.",None)]),
compare=dict(label="Then vs. now",h2="Traditional marketing vs. AI-era marketing",
  lead="The fundamentals of positioning and persuasion haven't changed. Almost everything about execution and discovery has.",
  cols=["","Traditional marketing","AI-era marketing"],
  rows=[["Discovery","Search results, ads and referrals","All of those, plus AI assistants recommending a shortlist"],
        ["Content","Produced slowly, by hand","Produced quickly, so judgment and editing are the bottleneck"],
        ["Advertising","Manual targeting and bidding","Algorithmic campaigns steered by your conversion data"],
        ["Advantage","Budget and production capacity","Clear positioning, a distinct voice and clean data"],
        ["Biggest risk","Being outspent","Sounding like everyone else"]]),
process=dict(label="How an engagement runs",h2="Diagnose, position, build, run, review",
  steps=[("Diagnose","Your numbers first: what a customer is worth, what one costs and where prospects drop off. Often the constraint isn't marketing at all."),
         ("Position","A clear statement of who you're for and why you're different. Everything AI produces gets checked against it."),
         ("Build the system","Voice guide, prompt library, content plan, tracking and the workflows that tie them together."),
         ("Run","Monthly production and campaigns, with AI handling volume and people approving everything public."),
         ("Review","A monthly written review tied to inquiries and revenue: what to stop, what to scale, what to test next.")]),
fit=dict(good=["Established businesses with a brand worth protecting","Small teams that need more output without more headcount","Companies spending on ads without knowing their cost per customer","Leaders who want marketing judged on revenue, not reach"],
         bad=["Anyone looking for the cheapest way to fill a content calendar","Brands unwilling to define a clear position first","Expectations of overnight growth from AI tools alone","Businesses wanting an agency to run everything unsupervised"]),
proof=dict(label="Track record",h2="Forty years, applied to the AI era",
  cards=[("8-year engagement","Blue Moon Fabrics","A single LA Fashion District store engineered into a national textile leader, the 100× build.","/bluemoon"),
         ("Consumer app","AisleBird","A voice-first grocery app grown across 500+ stores, marketed and built in-house.","/aislebird"),
         ("Reviews","5.0 on Google","Twelve public reviews from clients over more than a decade, every one verifiable.","/portfolio"),
         ("Local","LA & Napa Valley","AI marketing for Los Angeles and Napa Valley businesses, in person or online.","/ai-marketing-consultant-los-angeles")]),
faq=[("What does an AI marketing consultant do?","An AI marketing consultant decides where AI belongs in your marketing (research, content, advertising, personalization, measurement), sets up the systems and guardrails, and makes sure the result produces customers rather than just more content. The strategy is the job; the tools are the means."),
     ("Will AI-written content hurt my SEO?","Not because AI wrote it. Google's guidance is that it rewards helpful, reliable content however it's produced, while mass-produced, low-value content made to manipulate rankings breaks its spam policies. The risk is generic content, not the tool."),
     ("Do I still need a marketing agency?","Sometimes. If you need production capacity across many channels, an agency can provide it. What AI changes is that small teams can now do far more themselves, so many businesses need senior strategy and a good system more than they need another retainer."),
     ("Which AI marketing tools should we use?","Fewer than you'd think. Most businesses get the bulk of the value from one general-purpose AI assistant, the AI features already inside their ad platforms and CRM, and a good analytics setup. I recommend tools after the strategy, never before."),
     ("How do you keep AI content on-brand?","With a written voice system (a guide, approved examples and tuned prompts) and a rule that a person edits and approves everything public. That's what keeps a brand distinct when everyone has the same tools."),
     ("Do you work in my industry?","I've worked across legal, medical, dental, cosmetic surgery, ecommerce, hospitality, wine, textile, construction and professional services. See the <a href=\"/services\">services</a> and industry pages for specifics.")],
cta=("Make AI work for your brand, not against it","Book a free 30-minute call. We'll look at where AI would help your marketing most, and where it's already hurting it."),
))
